---
title: "Correlation CAT"
date: '`r Sys.time()`'
author: 'ETN'
output: 
  html_document: 
    toc: yes
    toc_float: true
---

```{r setup, include=FALSE}
library(ggpubr)
library(tidyverse)
library(dplyr)
knitr::opts_chunk$set(echo = FALSE)
load('corrcat.RData')
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

* Corr method -> Pearson

# Correlacio ISC 2019 ~ % immigrants
```{r, results='asis', fig.height = 8, fig.width = 10}
corr <- corr %>% select(ABS, Regi贸, `ISC 2019`, `% immigrants`,`CAODT_ 12a`, `codT_ 6_14a`, codAF_7, Perc_seg, IR_12a)
print(ggscatter(corr, x = '% immigrants', y = 'ISC 2019',  color = 'Regi贸',
        cor.coef = TRUE, cor.method = "pearson",
        xlab = '% immigrants', ylab = "ISC_2019") +
geom_smooth(method=lm, na.rm = TRUE, fullrange= TRUE,
            aes(group=1),colour="black"))
```


# Correlacio ISC 2019

```{r, results='asis', fig.height = 8, fig.width = 10}
cols = colnames(corr)
cols = cols[-c(1,2,3,4)]

for (i in cols) {
  cat(sprintf("\n\n## %s \n\n", i))
  print(ggscatter(corr, x = i, y = 'ISC 2019', color = 'Regi贸',
          cor.coef = TRUE, cor.method = "pearson",
          xlab = i, ylab = "ISC_2019") +
  geom_smooth(method=lm, na.rm = TRUE, fullrange= TRUE,
              aes(group=1),colour="black"))
   cat('----------------------------------------------------------------------------------------------------------------------------------------------------------------------------')
}

```

# Correlacio % immigrants

```{r, results='asis', fig.height = 8, fig.width = 10}
cols = colnames(corr)
cols = cols[-c(1,2,3,4)]

for (i in cols) {
  cat(sprintf("\n\n## %s \n\n", i))
  print(ggscatter(corr, x = i, y = '% immigrants', color = 'Regi贸',
          cor.coef = TRUE, cor.method = "pearson",
          xlab = i, ylab = "% immigrants") +
  geom_smooth(method=lm, na.rm = TRUE, fullrange= TRUE,
              aes(group=1),colour="black"))
   cat('----------------------------------------------------------------------------------------------------------------------------------------------------------------------------')
}

```