---
title: "Correlation GIR"
date: '`r Sys.time()`'
author: 'ETN'
output: 
  html_document: 
    toc: yes
    toc_float: true
---

```{r setup, include=FALSE}
library(ggpubr)
knitr::opts_chunk$set(echo = FALSE)
load('dadesgir.RData')
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

* Corr method -> Pearson

# Correlacio ISC ~ % immigrants

```{r, results='asis', fig.height = 8, fig.width = 10}
print(ggscatter(gir, x = 'Perc_immi', y = 'ISC', color = 'ABS',
        cor.coef = TRUE, cor.method = "pearson",
        xlab = '% immigrants', ylab = "ISC") +
geom_smooth(method=lm, na.rm = TRUE, fullrange= TRUE,
            aes(group=1),colour="black"))
```


# Correlacio ISC 2019

```{r, results='asis', fig.height = 8, fig.width = 10}
cols = colnames(gir)
cols = cols[-c(1,2,19,21)]

for (i in cols) {
  cat(sprintf("\n\n## %s \n\n", i))
  print(ggscatter(gir, x = i, y = 'ISC', color = 'ABS',
          cor.coef = TRUE, cor.method = "pearson",
          xlab = i, ylab = "ISC_2019") +
  geom_smooth(method=lm, na.rm = TRUE, fullrange= TRUE,
              aes(group=1),colour="black"))
   cat('----------------------------------------------------------------------------------------------------------------------------------------------------------------------------')
}

```

# Correlacio % immigrants

```{r, results='asis', fig.height = 8, fig.width = 10}
for (i in cols) {
  cat(sprintf("\n\n## %s \n\n", i))
  print(ggscatter(gir, x = i, y = 'Perc_immi', color = 'ABS',
          cor.coef = TRUE, cor.method = "pearson",
          xlab = i, ylab = "% immigrants") +
  geom_smooth(method=lm, na.rm = TRUE, fullrange= TRUE,
              aes(group=1),colour="black"))
   cat('----------------------------------------------------------------------------------------------------------------------------------------------------------------------------')
}

```